### ISSUE TITLE
If users share names across servers in conf, SAN is wrong for all certs

### ISSUE THREAD

**Issue by KaioKei** [LCailliot/easyssl#10]
example conf :

```yaml
platform:
  password: "secret123"
  hosts:
    - hostname: server1
      ip: 172.28.128.21
      users: ["server", "bob"]
    - users: ["server", "bob"]
      hostname: server2
      ip: 172.28.128.22
```
will generate certificates with the same dns resolution
