### ISSUE TITLE
Platform configuration YAML file

### ISSUE THREAD

**Issue by KaioKei** [LCailliot/easyssl#4]
# Configure platform

the script `platform_certs` SHOULD be launched with 

```sh
# python >= 3.8
python bin/platform.py --conf conf/platform.yml
```

The configuration must provide :

* [x] a root 'platform'
* [x] a list of material with :
    * [x] a name for each generated TLS material
    * [x] a host 
    * [x] an ip (for SAN configuration in certificates)
    * [x] a optional 'admin' conf with a boolean value (default false) -> add an admin certificate for this material

example :

```yaml
platform:
    - host: server1
      ip: 192.0.1.1
    - host: server2
      ip: 192.0.1.2
      admin: true
```
